hwi_oauth:
  firewall_names: [ main ]
  resource_owners:
    google:
      type: google
      client_id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
      client_secret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'
      scope: 'email profile'

    github:
      type: github
      client_id: '%env(OAUTH_GITHUB_CLIENT_ID)%'
      client_secret: '%env(OAUTH_GITHUB_CLIENT_SECRET)%'
      scope: 'user:email,public_repo'
