sonata_admin:
    title: 'Sonata Blog Admin'
    title_logo: 'app/img/f.ico'
    search: false
    templates:
        layout: 'admin/layout.html.twig'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            sonata.group.users:
                label: 'Users'
                items:
                    - sonata.user

            sonata.group.blog.posts:
                label: 'Edit blog'
                items:
                    - sonata.blog.posts

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

services:
    App\Controller\Admin\AdminCRUDController:
        tags: [container.service_subscriber]
        arguments:
          [ '@App\Service\Locker' ]

    sonata.user:
        class: App\Admin\UserAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\User, controller: App\Controller\Admin\AdminCRUDController, manager_type: orm, label: 'Users', show_mosaic_button: false }

    sonata.blog.posts:
        class: App\Admin\BlogPostAdmin
        arguments:
            - '@security.token_storage'
            - '@Cocur\Slugify\SlugifyInterface'
        tags:
            - { name: sonata.admin, model_class: App\Entity\BlogPost, controller: App\Controller\Admin\AdminCRUDController, manager_type: orm, label: 'Blog posts', show_mosaic_button: false }
