sonata_admin:
    title: 'Sonata Blog Admin'
    title_logo: 'app/img/f.ico'
    search: false
    templates:
        layout: 'admin/layout.html.twig'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

services:
    admin.user:
        class: App\Admin\UserWriter
        tags:
            - { name: sonata.admin, model_class: App\Entity\User, manager_type: orm, label: Users }

#    sonata.blog_posts:
#        class: App\Admin\BlogPostAdmin
#        arguments: [ ~, App\Entity\BlogPost, App\Admin\AppCRUDController ]
#        tags:
#            - { name: sonata.admin, manager_type: orm, label: Blog posts, show_mosaic_button: false }
#        calls:
#            - [ setTitle, [ '@App\Form\CreateBlogPost' ] ]
#            - [ setBody, [ '@App\Form\CreateBlogPost' ] ]
