version: '3.2'

services:
  php:
    build:
      dockerfile: ./docker/dev/php/Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
      - trash:/var/www/
    expose:
      - "9000"

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui
    platform: linux/amd64
    depends_on:
      - php

  nginx:
    image: nginx
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./docker/dev/nginx/symfony.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'

volumes:
  db:
  trash: