version: '3.2'

services:
  php:
    build:
      dockerfile: ./docker/dev/php/Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
      - trash:/var/www/
    container_name: ${PROJECT_NAME}-php
    expose:
      - "9000"
    environment:
      - PHP_IDE_CONFIG=serverName=Server

  php-messenger:
    build:
      dockerfile: ./docker/dev/php/Dockerfile
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./:/var/www/html
      - trash:/var/www/
    container_name: ${PROJECT_NAME}-php-messenger
    command: ["bin/console", "messenger:consume", "async", "-vv"]

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui
    container_name: ${PROJECT_NAME}-mailhog
    platform: linux/amd64
    depends_on:
      - php

  nginx:
    image: nginx
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./docker/dev/nginx/symfony.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    container_name: ${PROJECT_NAME}-nginx

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    container_name: ${PROJECT_NAME}-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    container_name: ${PROJECT_NAME}-redis

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    container_name: ${PROJECT_NAME}-rabbitmq

volumes:
  db:
  trash:
