controllers:
    resource: ../src/Controller/
    type: annotation

admin_controllers:
    resource: ../src/Controller/Admin/
    type: annotation
    prefix: /admin
    name_prefix: 'admin_'

app_controllers:
    resource: ../src/Controller/Public/
    type: annotation
    name_prefix: 'app_'

kernel:
    resource: ../src/Kernel.php
    type: annotation
