admin_controllers:
    resource: ../src/Controller/Admin/
    type: annotation
    prefix: /admin
    name_prefix: 'admin_'

app_controllers:
    resource: ../src/Controller/App/
    type: annotation
    prefix: /app
    name_prefix: 'app_'

kernel:
    resource: ../src/Kernel.php
    type: annotation
