controllers:
    resource: ../src/Controller/
    type: annotation

admin_controllers:
    resource: ../src/Controller/Admin/
    type: annotation

app_controllers:
    resource: ../src/Controller/App/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
